import type { AmlMember } from "@/modules/kyb/lib/aml-screening";

export const demoPrefillAnswers: Record<string, string> = {
  "1.1.1": "NexoPay S.A. de C.V.",
  "1.1.2": "Lic. Mariana Sofía Gutiérrez Salinas",
  "1.1.3": "188",
  "1.1.4": "32,784",
  "1.1.5": "Nuevo León",
  "1.1.6": "FME NL-2022031187",
  "1.1.7": "2022-03-11",
  "1.1.8": "NEX220311AB2",
  "1.1.9": "Mexicana",
  "1.1.10": "Sociedad Anónima de Capital Variable",
  "1.1.11": "Av. Lázaro Cárdenas 2400, Torre Nexus, Piso 8, Residencial San Agustín, San Pedro Garza García, C.P. 66260, Nuevo León, México",
  "1.1.12": "+52 81 8347 2200",
  "1.1.13": "cumplimiento@nexopay.com.mx",
  "1.1.14": "https://www.nexopay.com.mx",
  "1.2.1": "Pedro Antonio Velasco Mena",
  "1.2.2": "1985-06-21",
  "1.2.3": "Mexicana, México",
  "1.2.4": "Representante Legal",
  "1.2.6": "VEMP850621HNLLND09",
  "1.2.7": "VEMP850621LK2",
  "1.2.8": "Casado",
  "1.4.1": "Lic. Mariana Sofía Gutiérrez Salinas",
  "1.4.2": "188",
  "1.4.3": "32,784",
  "1.4.4": "Nuevo León",
  "1.4.5": "FME NL-2022031187",
  "1.4.6": "2022-03-11",
  "3.1.1": "https://dev.nexopay.com.mx/api, https://staging.nexopay.com.mx/api, https://sandbox.nexopay.com.mx/webhooks/zelify",
  "3.1.2": "sk_dev_nxp_83KslPq10Lm2, pk_dev_nxp_18QweLz55As9",
  "5.1.1": "No",
  "5.1.2": "No aplica",
  "5.2.1": "86",
  "5.2.2": "2",
  "5.3.1": "No",
  "5.3.2": "No aplica",
  "5.3.3": "No aplica",
  "5.3.4": "No",
  "5.4.1": "Privada",
  "5.4.2": "Plataforma de pagos empresariales, conciliación de cobros, dispersión y automatización financiera para comercios y empresas medianas.",
  "4.1.1":
    "Plataforma de pagos empresariales B2B: cobros, dispersión, conciliación y automatización financiera para comercios y PyMEs.",
  "4.1.2":
    "Empresas medianas en México con operación digital, retail, servicios y e-commerce con facturación recurrente.",
  "4.1.3":
    "Comisiones por transacción, suscripción mensual por volumen y servicios de valor agregado (conciliación y reportes).",
  "4.1.4":
    "Competidores: procesadores de pago y fintechs locales; diferenciador: onboarding KYB integrado y conciliación en tiempo real.",
  "4.1.5": "$18,500,000 MXN",
  "4.1.6": "$2,450 MXN",
  "4.1.7": "México (nacional); operaciones transfronterizas limitadas a cobros en USD vía clientes corporativos.",
};

export const demoDocumentSuggestions: Record<string, string> = {
  "1.2.5": "INE_Pedro_Antonio_Velasco_Mena.pdf",
  "1.2.9": "Comprobante_Domicilio_Pedro_Velasco_2026-05.pdf",
  "1.2.10": "Poder_Notarial_Representante_Legal_NexoPay.pdf",
  "1.5.5": "Identificaciones_Accionistas_y_Directivos_NexoPay.zip",
  "1.5.6": "Libro_Registro_Acciones_NexoPay.pdf",
  "1.6.1": "Acta_Constitutiva_y_Modificaciones_NexoPay.pdf",
  "1.6.2": "Constancia_Situacion_Fiscal_NexoPay_2026.pdf",
  "1.6.3": "Licencias_y_Registros_Regulatorios_NexoPay.zip",
  "2.1.1": "Manual_PLD_AML_NexoPay_2026.pdf",
  "2.1.2": "Politica_Datos_Personales_NexoPay.pdf",
  "3.2.1": "Diagrama_Flujo_Datos_NexoPay.pdf",
  "3.2.2": "Politica_Seguridad_Informacion_NexoPay.pdf",
  "3.2.3": "Certificaciones_NexoPay.zip",
  "3.2.4": "Documentacion_Procesos_NexoPay.pdf",
};

export const demoAmlMembers: AmlMember[] = [
  {
    id: "aml-seed-1",
    name: "Pedro Antonio Velasco Mena",
    email: "pedro.velasco@nexopay.com.mx",
    role: "CEO",
    ownershipPercent: 40,
    rfc: "VEMP850621LK2",
    curp: "VEMP850621HNLLND09",
    ineDocument: "INE_Pedro_Velasco.pdf",
    screeningStatus: "approved",
    screeningDetails: null,
  },
  {
    id: "aml-seed-2",
    name: "Gabriela Ruiz Téllez",
    email: "gabriela.ruiz@nexopay.com.mx",
    role: "CFO",
    ownershipPercent: 35,
    rfc: "RUTG880412JQ7",
    curp: "RUTG880412MNLRLB04",
    ineDocument: "INE_Gabriela_Ruiz.pdf",
    screeningStatus: "approved",
    screeningDetails: null,
  },
  {
    id: "aml-seed-4",
    name: "Inversiones Monte Claro, S.A. de C.V.",
    email: "accionistas@monteclaro.mx",
    role: "Socio / Accionista",
    ownershipPercent: 25,
    rfc: "IMC180920AB1",
    curp: "N/A",
    ineDocument: "Acta_Monte_Claro.pdf",
    screeningStatus: "approved",
    screeningDetails: null,
  },
  {
    id: "aml-seed-3",
    name: "Carlos Enrique Medina Lozano",
    email: "carlos.medina@nexopay.com.mx",
    role: "Presidente / Director",
    ownershipPercent: 0,
    rfc: "MELC790215HT5",
    curp: "MELC790215HDFRZR08",
    ineDocument: "INE_Carlos_Medina.pdf",
    screeningStatus: "approved",
    screeningDetails: null,
  },
];

export const demoKycMembers = [
  {
    id: "seed-member-1",
    name: "Pedro Antonio Velasco Mena",
    email: "pedro.velasco@nexopay.com.mx",
    role: "Representante Legal",
    rfc: "VEMP850621LK2",
    curp: "VEMP850621HNLLND09",
    kycStatus: "approved",
    kycDetails: null,
  },
  {
    id: "seed-member-2",
    name: "Gabriela Ruiz Téllez",
    email: "gabriela.ruiz@nexopay.com.mx",
    role: "CFO",
    rfc: "RUTG880412JQ7",
    curp: "RUTG880412MNLRLB04",
    kycStatus: "approved",
    kycDetails: null,
  },
];

export const demoSatFiscalData = {
  rfc: "NEX220311AB2",
  legalName: "NexoPay S.A. de C.V.",
  regime: "Régimen General de Ley Personas Morales (601)",
  status: "Activo",
  registrationDate: "2022-03-11",
  complianceOpinion: "Positive",
  complianceDetails: "El contribuyente se encuentra al corriente de sus obligaciones fiscales al día de hoy.",
  declarations: [
    { month: "Dic 2025", status: "Presentada", total: "$98,445.12" },
    { month: "Ene 2026", status: "Presentada", total: "$104,112.50" },
    { month: "Feb 2026", status: "Presentada", total: "$109,334.80" },
    { month: "Mar 2026", status: "Presentada", total: "$115,904.21" },
    { month: "Abr 2026", status: "Presentada", total: "$120,338.44" },
    { month: "May 2026", status: "Presentada", total: "$126,540.97" },
  ],
  averageIncome: "$112,446.01",
  financialHealthScore: "A",
  riskIndicator: "Bajo",
  yearsActive: 4,
};

export const demoSatCredentials = {
  rfc: "NEX220311AB2",
  password: "NexoSatDemo2026!",
};
