import type { AmlMember } from "@/modules/kyb/lib/aml-screening";

export const demoPrefillAnswers: Record<string, string> = {
  "1.1.1": "GRUPO DELTA INDUSTRIAL SA DE CV",
  "1.1.2": "Lic. Verónica Elena Cárdenas Ruiz",
  "1.1.3": "214",
  "1.1.4": "41,982",
  "1.1.5": "Nuevo León",
  "1.1.6": "FME NL-2022051821",
  "1.1.7": "2022-05-18",
  "1.1.8": "MOR220518KJ4",
  "1.1.9": "Mexicana",
  "1.1.10": "Sociedad Anónima de Capital Variable",
  "1.1.11": "Parque Industrial Mitras Norte, Nave 14, Av. Industria Metalúrgica 480, García, C.P. 66023, Nuevo León, México",
  "1.1.12": "+52 81 8624 1180",
  "1.1.13": "planeacion@orionmanufactura.mx",
  "1.1.14": "https://www.orionmanufactura.mx",
  "1.2.1": "Alejandro Torres Valdez",
  "1.2.2": "1982-04-17",
  "1.2.3": "Mexicana, México",
  "1.2.4": "Representante Legal",
  "1.2.6": "TOVA820417HNLRLL08",
  "1.2.7": "TOVA820417QF1",
  "1.2.8": "Casado",
  "1.4.1": "Lic. Verónica Elena Cárdenas Ruiz",
  "1.4.2": "214",
  "1.4.3": "41,982",
  "1.4.4": "Nuevo León",
  "1.4.5": "FME NL-2022051821",
  "1.4.6": "2022-05-18",
  "3.1.1": "https://erp.orionmanufactura.mx/api/zelify, https://portal.orionmanufactura.mx/webhooks/credito, https://sandbox.orionmanufactura.mx/api",
  "3.1.2": "sk_dev_orion_72LmQp911, pk_dev_orion_18QaZp440",
  "5.1.1": "No",
  "5.1.2": "No aplica",
  "5.2.1": "148",
  "5.2.2": "3",
  "5.3.1": "No",
  "5.3.2": "No aplica",
  "5.3.3": "No aplica",
  "5.3.4": "No",
  "5.4.1": "Privada",
  "5.4.2": "Fabricación y ensamblaje de componentes metálicos de precisión para industria automotriz, infraestructura y equipo industrial.",
  "4.1.1":
    "Fabricación B2B de piezas y subconjuntos metálicos para clientes industriales, con contratos de suministro recurrentes y producción bajo especificación.",
  "4.1.2":
    "OEMs, constructoras industriales y distribuidores nacionales con operación en manufactura, infraestructura eléctrica y autopartes.",
  "4.1.3":
    "Ingresos por órdenes de producción, contratos marco de suministro y servicios de corte, doblado y ensamble especializados.",
  "4.1.4":
    "Competidores: talleres metalmecánicos regionales y fabricantes especializados; diferenciador: integración vertical, entregas just-in-time y trazabilidad por lote.",
  "4.1.5": "$126,000,000 MXN",
  "4.1.6": "$148,000 MXN",
  "4.1.7": "México (nacional) con envíos recurrentes a Nuevo León, Coahuila, Querétaro y Jalisco.",
};

export const demoDocumentSuggestions: Record<string, string> = {
  "1.2.5": "INE_Alejandro_Torres_Valdez.pdf",
  "1.2.9": "Comprobante_Domicilio_Alejandro_Torres_2026-05.pdf",
  "1.2.10": "Poder_Notarial_Representante_Legal_Manufacturas_Orion.pdf",
  "1.5.5": "Identificaciones_Accionistas_y_Directivos_Manufacturas_Orion.zip",
  "1.5.6": "Libro_Registro_Acciones_Manufacturas_Orion.pdf",
  "1.6.1": "Acta_Constitutiva_y_Modificaciones_Manufacturas_Orion.pdf",
  "1.6.2": "Constancia_Situacion_Fiscal_Manufacturas_Orion_2026.pdf",
  "1.6.3": "Licencias_y_Registros_Regulatorios_Manufacturas_Orion.zip",
  "2.1.1": "Manual_PLD_AML_Manufacturas_Orion_2026.pdf",
  "2.1.2": "Politica_Datos_Personales_Manufacturas_Orion.pdf",
  "3.2.1": "Diagrama_Flujo_Datos_Manufacturas_Orion.pdf",
  "3.2.2": "Politica_Seguridad_Informacion_Manufacturas_Orion.pdf",
  "3.2.3": "Certificaciones_Manufacturas_Orion.zip",
  "3.2.4": "Documentacion_Procesos_Manufacturas_Orion.pdf",
};

export const demoAmlMembers: AmlMember[] = [
  {
    id: "aml-seed-1",
    name: "Alejandro Torres Valdez",
    email: "direccion.general@orionmanufactura.mx",
    role: "Representante Legal",
    ownershipPercent: 40,
    rfc: "TOVA820417QF1",
    curp: "TOVA820417HNLRLL08",
    ineDocument: "INE_Alejandro_Torres_Valdez.pdf",
    screeningStatus: "approved",
    screeningDetails: null,
  },
  {
    id: "aml-seed-2",
    name: "Mariana del Carmen Salcedo",
    email: "finanzas@orionmanufactura.mx",
    role: "CFO",
    ownershipPercent: 35,
    rfc: "SACM860912LM2",
    curp: "SACM860912MNLLRL03",
    ineDocument: "INE_Mariana_Salcedo.pdf",
    screeningStatus: "approved",
    screeningDetails: null,
  },
  {
    id: "aml-seed-4",
    name: "Grupo Orion Industrial Holding, S.A. de C.V.",
    email: "accionistas@orionholding.mx",
    role: "Socio / Accionista",
    ownershipPercent: 25,
    rfc: "GOI180920AB1",
    curp: "N/A",
    ineDocument: "Acta_Grupo_Orion_Industrial_Holding.pdf",
    screeningStatus: "approved",
    screeningDetails: null,
  },
  {
    id: "aml-seed-3",
    name: "Ricardo Emilio Garza Flores",
    email: "operaciones@orionmanufactura.mx",
    role: "Presidente / Director",
    ownershipPercent: 0,
    rfc: "GAFR790215HT5",
    curp: "GAFR790215HNLRLC06",
    ineDocument: "INE_Ricardo_Garza.pdf",
    screeningStatus: "approved",
    screeningDetails: null,
  },
];

export const demoKycMembers = [
  {
    id: "seed-member-1",
    name: "Alejandro Torres Valdez",
    email: "direccion.general@orionmanufactura.mx",
    role: "Representante Legal",
    rfc: "TOVA820417QF1",
    curp: "TOVA820417HNLRLL08",
    kycStatus: "approved",
    kycDetails: null,
  },
  {
    id: "seed-member-2",
    name: "Mariana del Carmen Salcedo",
    email: "finanzas@orionmanufactura.mx",
    role: "CFO",
    rfc: "SACM860912LM2",
    curp: "SACM860912MNLLRL03",
    kycStatus: "approved",
    kycDetails: null,
  },
];

export const demoSatFiscalData = {
  rfc: "MOR220518KJ4",
  legalName: "GRUPO DELTA INDUSTRIAL SA DE CV",
  regime: "Régimen General de Ley Personas Morales (601)",
  status: "Activo",
  registrationDate: "2022-05-18",
  complianceOpinion: "Positive",
  complianceDetails: "El contribuyente se encuentra al corriente de sus obligaciones fiscales al día de hoy.",
  declarations: [
    { month: "Dic 2025", status: "Presentada", total: "$8,944,512.43" },
    { month: "Ene 2026", status: "Presentada", total: "$9,142,308.55" },
    { month: "Feb 2026", status: "Presentada", total: "$9,338,924.12" },
    { month: "Mar 2026", status: "Presentada", total: "$9,556,011.89" },
    { month: "Abr 2026", status: "Presentada", total: "$9,765,432.70" },
    { month: "May 2026", status: "Presentada", total: "$9,972,110.36" },
  ],
  averageIncome: "$9,453,216.68",
  financialHealthScore: "A+",
  riskIndicator: "Bajo",
  yearsActive: 4,
};

export const demoSatCredentials = {
  rfc: "MOR220518KJ4",
  password: "OrionSatDemo2026!",
};
